import '../../js/std-js/shims/globalThis.js';
import '../../js/std-js/shims/abort.js';
import '../../js/std-js/shims/element.js';
import '../../js/std-js/shims/function.js';
import '../../js/std-js/shims/promise.js';
import '../../js/std-js/shims/trustedTypes.js';
import '../../js/std-js/shims/sanitizer.js';
import '../../js/std-js/shims/scheduler.js';
import './events.js';
